send-review-commit: Be more expressive on errors
Change-Id: I29734f48206959bdc99d01f768115e55b8457549

diff --git a/scripts/git-gerrit-send-review-commit b/scripts/git-gerrit-send-review-commit
--- a/scripts/git-gerrit-send-review-commit
+++ b/scripts/git-gerrit-send-review-commit
@@ -65,11 +65,19 @@ git checkout -b picked_commits
 
 for commit in "$@"; do
   if [ -e "$commit" ]; then
-    echo "Applying $commit"
-    git am "$commit" || exit 1
+    echo "Applying: " $(git log --oneline -1 $commit)
+    git am "$commit"
   else
-    echo "Picking $commit"
-    git cherry-pick $commit || exit 1
+    echo "Picking: " $(git log --oneline -1 $commit)
+    git cherry-pick $commit
+  fi
+
+  if [ $? != 0 ]; then
+    echo
+    echo "Failed to apply:"
+    git status
+    git diff
+    exit 1
   fi
 done
 
